repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml

template:
  org: nf-core
  name: ribomsqc
  description: QC pipeline that monitors mass spectrometer performance in ribonucleoside
    analysis
  author: Roger Olivella
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  is_nfcore: true
