contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ribomsqc channel"
    url: https://nfcore.slack.com/channels/ribomsqc
    about: Discussion about the nf-core/ribomsqc pipeline
